  config:
    target: "ws://p7-webserver.herokuapp.com"
    phases:
      - duration: 10
        arrivalRate: 50
    ws:
      # Ignore SSL certificate errors
      # - useful in *development* with self-signed certs
      rejectUnauthorized: false
  scenarios:
    - engine: "ws"
      flow:
        - send: "{\"options\": {\"type\": \"host_connection\"}}"
        - think: 10